services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017

  db:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: